import { useState } from 'react';
import JSZip from 'jszip';
import { Download } from 'lucide-react';

// Root files
import packageJson from '../../package.json?raw';
import tsconfigJson from '../../tsconfig.json?raw';
import viteConfig from '../../vite.config.ts?raw';
import gitIgnore from '../../.gitignore?raw';
import envExample from '../../.env.example?raw';
import metadataJson from '../../metadata.json?raw';
import indexHtml from '../../index.html?raw';
import readmeMd from '../../README.md?raw';

// Public files
import manifestJson from '../../public/manifest.json?raw';
import swJs from '../../public/sw.js?raw';
import iconSvg from '../../public/icon.svg?raw';

// Src Root files
import appTsx from '../App.tsx?raw';
import mainTsx from '../main.tsx?raw';
import indexCss from '../index.css?raw';

// Src Lib & Hooks
import utilsTs from '../lib/utils.ts?raw';
import useSettingsTs from '../hooks/useSettings.ts?raw';
import useHistoryTs from '../hooks/useHistory.ts?raw';

// Src Components
import dashboardViewTsx from './DashboardView.tsx?raw';
import settingsViewTsx from './SettingsView.tsx?raw';
import historiqueViewTsx from './HistoriqueView.tsx?raw';
import listManagerTsx from './ListManager.tsx?raw';
import taskManagerTsx from './TaskManager.tsx?raw';
import selectTsx from './Select.tsx?raw';
import multiSelectTsx from './MultiSelect.tsx?raw';

export function EmergencyExportButton() {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async () => {
    setIsExporting(true);
    try {
      const zip = new JSZip();

      // Folder Structure
      const publicFolder = zip.folder("public");
      const srcFolder = zip.folder("src");
      const componentsFolder = srcFolder!.folder("components");
      const hooksFolder = srcFolder!.folder("hooks");
      const libFolder = srcFolder!.folder("lib");
      const githubFolder = zip.folder(".github");
      const workflowsFolder = githubFolder!.folder("workflows");

      // Root files
      zip.file("package.json", packageJson);
      zip.file("tsconfig.json", tsconfigJson);
      zip.file("vite.config.ts", viteConfig);
      zip.file(".gitignore", gitIgnore);
      zip.file(".env.example", envExample);
      zip.file("metadata.json", metadataJson);
      zip.file("index.html", indexHtml);
      zip.file("README.md", readmeMd);

      // Public files
      publicFolder!.file("manifest.json", manifestJson);
      publicFolder!.file("icon.svg", iconSvg);
      publicFolder!.file("sw.js", swJs);
      publicFolder!.file(".nojekyll", "");

      // Src Root
      srcFolder!.file("App.tsx", appTsx);
      srcFolder!.file("main.tsx", mainTsx);
      srcFolder!.file("index.css", indexCss);

      // Src Lib & Hooks
      libFolder!.file("utils.ts", utilsTs);
      hooksFolder!.file("useSettings.ts", useSettingsTs);
      hooksFolder!.file("useHistory.ts", useHistoryTs);

      // Src Components
      componentsFolder!.file("DashboardView.tsx", dashboardViewTsx);
      componentsFolder!.file("SettingsView.tsx", settingsViewTsx);
      componentsFolder!.file("HistoriqueView.tsx", historiqueViewTsx);
      componentsFolder!.file("ListManager.tsx", listManagerTsx);
      componentsFolder!.file("TaskManager.tsx", taskManagerTsx);
      componentsFolder!.file("Select.tsx", selectTsx);
      componentsFolder!.file("MultiSelect.tsx", multiSelectTsx);
      componentsFolder!.file("EmergencyExportButton.tsx", `// This file is auto-generated by export\nexport function EmergencyExportButton() { return null; }`);

      // GitHub Actions Deployment Workflow
      workflowsFolder!.file("deploy.yml", `name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`);

      // Trigger Download
      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "sme-cadex-gh-pages.zip";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
    } catch (error) {
      console.error("Export failed:", error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={isExporting}
      className="flex items-center gap-2 bg-gradient-to-r from-amber-600 to-amber-700 hover:from-amber-500 hover:to-amber-600 text-white px-5 py-2.5 rounded-sm border border-amber-500/50 transition-all shadow-md font-bold text-sm ml-2 group"
      title="Download Source for GitHub"
    >
      <Download className="w-4 h-4 group-hover:-translate-y-0.5 transition-transform" />
      <span className="hidden sm:inline">{isExporting ? 'Preparing Archive...' : 'Download Source for GitHub'}</span>
    </button>
  );
}
